### ISSUE TITLE
Cargo

### ISSUE THREAD

**Issue by jklmnn** [p-e-w/ternimal#3]
While you've stated that it doesn't depend on cargo you could still provide it. This would make it probably easier for new users to access this project.
Beside that providing cargo doesn't make the project depend on it, you could still build the project with plain rustc.
@xTibor already added a cargo build in his repository (https://github.com/xTibor/ternimal/commit/47c36116258385835dc88153046367c9bdbf103e).

**Comment by xTibor** [comment]
I agree, it would be handy to have Cargo support. However my reason for cargolizing the project on that branch was to be able to cross-compile it with Xargo for Redox.

**Comment by p-e-w** [comment]
Perhaps I'm missing something – what exactly would be the benefit here?

There are no dependencies to fetch, nothing to incrementally compile (as there is only one source file), no tests to run... AFAICT the only difference would be that you compile with `cargo build --release` instead of `rustc -O ternimal.rs`.

That being said, running this on Redox sounds exciting. Please post screenshots if you get it to work!

**Comment by jklmnn** [comment]
Beside making the entry for new users easier (most people I think are used to cargo build/run/install) it also makes porting easier (as @xTibor said) and it would open the possibility (if uploaded to crates.io) to install it directly via cargo.
Also it would prevent that people need to add cargo each time they need it on their own.

Apart from that I've read your README and I'm totally Ok with it if you say no just because you don't want to have cargo ;)

**Comment by robinst** [comment]
Another reason for using cargo is that you can use IDE things such as [IntelliJ Rust](https://intellij-rust.github.io/) or VS Code with the [RLS plugin](https://github.com/rust-lang-nursery/rls-vscode) for editing the project and you get error reporting and code analysis and all those things.

(Also, having a `Cargo.toml` doesn't prevent you from still running `rustc -O ternimal.rs` if you want.)

**Comment by p-e-w** [comment]
Based on the information in this issue, I have decided not to add Cargo support at this time.

I like the minimal repository layout too much and I just don't feel the advantages of Cargo outweigh that for me.

**Comment by robinst** [comment]
There's a fork with cargo added here: https://github.com/xTibor/ternimal-cargo

With that, installation is really simple, just run `cargo install --git https://github.com/xTibor/ternimal-cargo`
