### ISSUE TITLE
Works fine on windows using the Windows Linux Subsystem

### ISSUE THREAD

**Issue by cdgiessen** [p-e-w/ternimal#4]
Works like I expected.

No problems compiling it (once I had the right compiler setup) and no issue running it.

Very neat program!

**Comment by p-e-w** [comment]
Thanks!

**Comment by Pjaerr** [comment]
Also works okay on ConEmu on windows.

**Comment by smackysnacks** [comment]
Works with PowerShell too!

**Comment by p-e-w** [comment]
@rmbreak Really? I didn't know PowerShell supports ANSI escape sequences. Does it render true color also or just 256 colors? Could you post a screenshot?

**Comment by smackysnacks** [comment]
@p-e-w 

![powershell](https://user-images.githubusercontent.com/587223/32691063-4bb63a0c-c6d0-11e7-963f-7811931119eb.PNG)

**Comment by p-e-w** [comment]
Thanks for the feedback everyone! I have added this information to the README.
