### ISSUE TITLE
Can it work in background and interact with other characters being outputted?

### ISSUE THREAD

**Issue by vi** [p-e-w/ternimal#5]
It would be even nicer if one could Ctrl+Z to continue issuing more Bash/whatever commands (or even start ncurses things like Vim), yet background Ternimal still lived and also perceived non-whitespace characters as walls.

**Comment by p-e-w** [comment]
Cool idea, but unfortunately impossible to implement. Terminal emulators do not provide a way for programs to read characters at terminal cells, so Ternimal cannot "see" those walls.

**Comment by vi** [comment]
So it can allocate a pseudo-terminal itself, like `/usr/bin/script`.

**Comment by p-e-w** [comment]
Yeah, but that would be a bit out of scope for this project ;)
