### ISSUE TITLE
It's glitchy in lxterminal

### ISSUE THREAD

**Issue by mrowlbio** [p-e-w/ternimal#9]
In lubuntu using lxterminal it's glitchy 
it's going off color and skipping blocks like this

![2018-02-22-185848_1440x900_scrot](https://user-images.githubusercontent.com/28918634/36541106-d6194986-1802-11e8-8162-942c1d9fe053.png)

also, I built it from source (if that helps debug)

**Comment by Lonsfor** [comment]
https://github.com/p-e-w/ternimal#why-am-i-seeing-randomweird-colors

**Comment by mrowlbio** [comment]
oh,thanks
